export const GET_INDICATORS_FAILURE = ' GET_INDICATORS_FAILURE'
export const GET_INDICATORS_SUCCESS = 'GET_INDICATORS_SUCCESS'
export const GET_INDICATORS_REQUEST = 'GET_INDICATORS_REQUEST'

export const GET_ONE_INDICATORS_FAILURE = ' GET_ONE_INDICATORS_FAILURE'
export const GET_ONE_INDICATORS_SUCCESS = 'GET_ONE_INDICATORS_SUCCESS'
export const GET_ONE_INDICATORS_REQUEST = 'GET_ONE_INDICATORS_REQUEST'

export const SET_INDICATOR = 'SET_INDICATOR'